blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/greenstevester/yetanotherhueapi#readme
    about: Read the project documentation and examples
  - name: Philips Hue Developer Portal
    url: https://developers.meethue.com/
    about: Official Philips Hue API documentation
  - name: Discussions
    url: https://github.com/greenstevester/yetanotherhueapi/discussions
    about: Community discussions and general questions