name: Feature Request
description: Suggest a new feature or enhancement for the Hue API library
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - greenstevester

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 
        
        Please search existing issues first to avoid duplicates.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you want...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        I'm always frustrated when...
        This feature would help with...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        I would like to see...
        The API could work like this...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or workarounds you've considered
      placeholder: |
        Alternative approaches could be...
        Current workarounds include...
    validations:
      required: false

  - type: dropdown
    id: api-version
    attributes:
      label: Target API Version
      description: Which Hue API version should this feature target?
      options:
        - "V2 (preferred)"
        - "V1 (legacy)"
        - "Both"
        - "New API version"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would be helpful"
        - "High - Important for my use case"
        - "Critical - Blocking my project"
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Example Usage
      description: Show how you would like to use this feature in code
      render: java
      placeholder: |
        // Example of how the feature might be used
        HueBridge bridge = HueBridge.discover().get(0);
        bridge.newFeature().doSomething();
    validations:
      required: false

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - label: New API method/functionality
        - label: Performance improvement
        - label: Developer experience enhancement
        - label: Documentation improvement
        - label: Testing improvement
        - label: Security enhancement
        - label: Compatibility improvement

  - type: textarea
    id: hue-documentation
    attributes:
      label: Philips Hue Documentation
      description: If this feature is based on official Hue API documentation, please provide links
      placeholder: |
        Links to official Philips Hue API documentation:
        - https://developers.meethue.com/...
    validations:
      required: false

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Considerations
      description: Any thoughts on implementation challenges or requirements?
      placeholder: |
        This might require...
        Potential challenges could be...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I'm willing to work on this feature
        - label: I can help with testing
        - label: I can help with documentation
        - label: I can provide feedback during development

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I have provided a clear description of the problem and solution
          required: true