name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type of update to perform'
        required: true
        default: 'minor'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  check-dependencies:
    name: Check for Dependency Updates
    runs-on: ubuntu-latest
    
    outputs:
      updates-available: ${{ steps.check.outputs.updates-available }}
      security-updates: ${{ steps.security-check.outputs.security-updates }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Check for dependency updates
      id: check
      run: |
        mvn versions:display-dependency-updates > dependency-updates.txt
        mvn versions:display-plugin-updates > plugin-updates.txt
        
        if grep -q "The following dependencies in Dependencies have newer versions:" dependency-updates.txt; then
          echo "updates-available=true" >> $GITHUB_OUTPUT
        else
          echo "updates-available=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Check for security updates
      id: security-check
      run: |
        mvn org.owasp:dependency-check-maven:check -DfailBuildOnAnyVulnerability=false
        
        if [ -f "target/dependency-check-report.json" ]; then
          vulnerabilities=$(jq '.dependencies[].vulnerabilities | length' target/dependency-check-report.json | awk '{sum+=$1} END {print sum}')
          if [ "$vulnerabilities" -gt 0 ]; then
            echo "security-updates=true" >> $GITHUB_OUTPUT
          else
            echo "security-updates=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "security-updates=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-reports
        path: |
          dependency-updates.txt
          plugin-updates.txt
          target/dependency-check-report.*
        retention-days: 7

  security-updates:
    name: Create Security Update PR
    runs-on: ubuntu-latest
    needs: check-dependencies
    if: needs.check-dependencies.outputs.security-updates == 'true'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Update dependencies with security fixes
      run: |
        # Update patch versions for security fixes
        mvn versions:use-latest-releases -DallowSnapshots=false -DgenerateBackupPoms=false
        
        # Check if any changes were made
        if git diff --quiet pom.xml; then
          echo "No security updates needed"
          exit 0
        fi
    
    - name: Run tests with updated dependencies
      run: mvn clean test
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'security: update dependencies with security fixes'
        title: 'Security: Update dependencies with known vulnerabilities'
        body: |
          This PR contains security updates for dependencies with known vulnerabilities.
          
          ## Changes
          - Updated dependencies to latest secure versions
          - All tests are passing
          
          ## Security Impact
          This update addresses known security vulnerabilities in our dependencies.
          
          **This PR should be reviewed and merged as soon as possible.**
          
          Auto-generated by dependency-updates workflow.
        branch: security/dependency-updates
        delete-branch: true
        draft: false
        labels: |
          security
          dependencies
          automated

  regular-updates:
    name: Create Regular Update PR
    runs-on: ubuntu-latest
    needs: check-dependencies
    if: needs.check-dependencies.outputs.updates-available == 'true' && needs.check-dependencies.outputs.security-updates == 'false'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Update dependencies
      run: |
        UPDATE_TYPE="${{ github.event.inputs.update_type || 'minor' }}"
        
        case $UPDATE_TYPE in
          "patch")
            mvn versions:use-latest-releases -DallowIncrementalUpdates=false -DallowMinorUpdates=false -DallowMajorUpdates=false
            ;;
          "minor")
            mvn versions:use-latest-releases -DallowIncrementalUpdates=true -DallowMinorUpdates=true -DallowMajorUpdates=false
            ;;
          "major")
            mvn versions:use-latest-releases -DallowIncrementalUpdates=true -DallowMinorUpdates=true -DallowMajorUpdates=true
            ;;
        esac
        
        # Update plugin versions
        mvn versions:use-latest-versions -DallowSnapshots=false -DgenerateBackupPoms=false
        
        # Check if any changes were made
        if git diff --quiet pom.xml; then
          echo "No updates available"
          exit 0
        fi
    
    - name: Run tests with updated dependencies
      id: test
      continue-on-error: true
      run: mvn clean test
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'deps: update dependencies and plugins'
        title: 'Dependencies: Update to latest versions'
        body: |
          This PR updates dependencies and Maven plugins to their latest versions.
          
          ## Changes
          - Updated dependencies to latest ${{ github.event.inputs.update_type || 'minor' }} versions
          - Updated Maven plugins to latest versions
          
          ## Test Results
          Tests: ${{ steps.test.outcome }}
          
          ${{ steps.test.outcome == 'failure' && '⚠️ **Note**: Tests are failing with the updated dependencies. Please review the changes carefully.' || '✅ All tests are passing with the updated dependencies.' }}
          
          Auto-generated by dependency-updates workflow.
        branch: deps/regular-updates
        delete-branch: true
        draft: ${{ steps.test.outcome == 'failure' }}
        labels: |
          dependencies
          automated

  dependency-monitoring:
    name: Monitor Critical Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Check critical dependencies
      run: |
        # Define critical dependencies to monitor
        CRITICAL_DEPS=(
          "com.fasterxml.jackson.core:jackson-databind"
          "org.slf4j:slf4j-api"
          "com.launchdarkly:okhttp-eventsource"
        )
        
        echo "# Critical Dependency Status" >> dependency-status.md
        echo "" >> dependency-status.md
        
        for dep in "${CRITICAL_DEPS[@]}"; do
          current_version=$(mvn dependency:list | grep "$dep" | head -1 | sed 's/.*://' | sed 's/:compile.*//')
          echo "- $dep: $current_version" >> dependency-status.md
        done
    
    - name: Create/Update Dependency Status Issue
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: 1  # Update this to track in a specific issue
        body-path: dependency-status.md